# A generic, single database configuration.

[alembic]
# Path to migration scripts
script_location = alembic

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# Truncate revision to 12 chars
truncate_slug_length = 40

# Set to 'true' to run the environment during the 'revision' command
revision_environment = false

# Set to 'true' to allow .pyc and .pyo files without a source .py file
sourceless = false

# Version table name
version_table = alembic_version

# The output encoding used in new migration files
output_encoding = utf-8

# sqlalchemy.url is set programmatically in env.py from our Settings
sqlalchemy.url = driver://user:pass@localhost/dbname
